### ISSUE TITLE
2º Meetup Vue.js Floripa: Talks

### ISSUE THREAD

**Issue by danilowoz** [VueFloripa/Meetup#1]
Envie sua proposta comentando nesta Issue!

## Sugestão de template:

**Título da palestra:**

**Público alvo:**
- Iniciante
- Intermediário 
- Avançado

**Formato:**
- Light (20min) 
- Talk (40min) 

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**

Markdown:
```
**Título da palestra:**

**Público alvo:**

**Formato:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by klarkc** [comment]
**Título da palestra:** Documentação de componentes usando o vue-styleguidist

**Público alvo:** Qualquer pessoa com conhecimentos introdutórios do funcionamento do Vuejs

**Formato:** Light (20min)

**Nome do Palestrante:** Walker Gusmão Leite

**Resumo da palestra:** Mostrarei como documentar o código usando o padrão jsdoc, como usar o vue-styleguidist para gerar um servidor de documentação com exemplos de uso, livecoding, e para compilar a documentação. Finalizarei mostrando o template do Vue que criei para documentar componentes usando todos os conceitos abordados.

**Material (Se houver):**
- https://github.com/vue-styleguidist/vue-styleguidist
- https://github.com/InCuca/vue-standalone-component

---

**Link talk:** 
https://docs.google.com/presentation/d/1G4DSIBo3aaw_GTBXQUJ9YdytsUMo59cvLTV2ssGBL_I/edit#slide=id.p

**Comment by bernardocs** [comment]
**Título da palestra:** Iniciando em Vue usando `vue-cli`

**Público alvo:** Iniciante

**Formato:** Light (20min)

**Nome do Palestrante:** Bernardo Santos

**Resumo da palestra:** Uma pequena demonstração (provavelmente live coding) em como iniciar de forma rápida e simples um projeto Vue usando `vue-cli`.

**Material (Se houver):** https://github.com/vuejs/vue-cli

---
**Link talk:** https://docs.google.com/presentation/d/1b94vAVnGPHU5n11sydvXehUKEFqUF4LPv1-X_g92n58/edit

**Comment by ghost** [comment]
**Título da palestra:** O que é vuex e para que ele serve

**Público alvo:** Qualquer pessoa com conhecimentos intermediários do funcionamento do Vuejs, React ou Flux/Redux

**Formato:** Light (20min)

**Nome do Palestrante:** Christian Barros Fabião do Nascimento

**Resumo da palestra:** Quando nossa aplicação cresce fica difícil manusear o estado de vários componentes e interações entre eles. Para resolver este problema, o Vue oferece o vuex: Uma biblioteca de gerenciamento de estado inspirada no Flux, Redux e na arquitetura Elm. Falarei um pouco sobre a mesma e os problemas que ele resolve.

**Material (Se houver):**
https://vuex.vuejs.org/en/

---
**Link talk:** https://speakerdeck.com/cnascimentord/o-que-e-vuex-e-para-que-ele-serve-2
