### ISSUE TITLE
8º Meetup Vue.js Floripa

### ISSUE THREAD

**Issue by itsweliton** [VueFloripa/Meetup#10]
Para submeter sua talk baste responder essa issue com o template abaixo.
Vamos selecionar as talks com base na quatidade de 👍 que elas tiverem, portanto vote nas talks que você gostaria de ver no dia do Meetup!

Título (OBRIGATÓRIO)
Resumo (OBRIGATÓRIO)
[Um parágrafo resumindo o conteúdo geral da sua talk.]

Duração (OBRIGATÓRIO)
[Tempo aproximado de duração da sua talk.] --> Usaremos para ajustar no tempo de auditório disponível.

Comentários (OPCIONAL)
[Informações extras em relação a sua talk, inclusive motivação para falar desse assunto e porquê o assunto é interessante.]
Limite para envio: 10/11

**Comment by LucasLeandro1204** [comment]
# Vue Rewind - Retrospectiva

Talk mostrando em ordem cronológica o que aconteceu em torno / com o nosso querido framework neste ano, passando pelos seguintes tópicos:

- Releases
- Features novas do Framework
- Mudanças de API
- Tretas
- Estado do Vue 3 (proposals / next)

Aproximadamente 25 - 35 minutos

**Comment by viniciuskneves** [comment]
# Let's eat Brotli

Brotli já está disponível no "mercado" a um bom tempo. Pretendo mostrar como implementamos Brotli e quais foram os resultados, além dos desafios que enfrentamos e quais seriam os próximos passos.

~30 - 40 minutos

_Apresentei o mesmo assunto no VueBerlin de julho desse ano, então pretendo usar praticamente a mesma apresentação que está em inglês.
O projeto em questão é um SPA em Vue, porém o foco da talk é falar um pouco de DevOps no frontend e como podemos nos beneficiar disso._

**Comment by klarkc** [comment]
# Vue Hooks

Os hooks mudam a forma como declaramos as opções na criação dos componentes . Vamos entender o que muda no Vue 3 e porque usar essa nova feature. 

30 minutos
