### ISSUE TITLE
9º Meetup VueFloripa

### ISSUE THREAD

**Issue by itsweliton** [VueFloripa/Meetup#11]
Para submeter sua talk baste responder essa issue com o template abaixo.
Vamos selecionar as talks com base na quatidade de 👍 que elas tiverem, portanto vote nas talks que você gostaria de ver no dia do Meetup!

Título (OBRIGATÓRIO)
Resumo (OBRIGATÓRIO)
[Um parágrafo resumindo o conteúdo geral da sua talk.]

Duração (OBRIGATÓRIO)
[Tempo aproximado de duração da sua talk.] --> Usaremos para ajustar no tempo de auditório disponível.

Comentários (OPCIONAL)
[Informações extras em relação a sua talk, inclusive motivação para falar desse assunto e porquê o assunto é interessante.]
Limite para envio: 10/11

**Comment by thiagovictorino** [comment]
Título
Acelere suas pesquisas com Algolia

Resumo 
O Algolia é uma plataforma de pesquisa-as-a-service que habilita empresas de todos os tamanhos a entregarem uma experiência fenomenal de busca de conteúdo, possui uma biblioteca escrita em VueJS de fácil aplicação. A palestra tem como objetivo mostrar um caso de uso da ferramenta em sites como flat.com.br e shortstay.com.br e como fazer um 'hello word' dentro da plataforma.

Duração 
30 minutos.

Comentários 
O site da ferramenta é  [https://www.algolia.com](https://www.algolia.com) e falarei sobre o [Instant Search](https://www.algolia.com/products/instantsearch/) e sobre a biblioteca [https://www.algolia.com/doc/guides/building-search-ui/getting-started/vue/](VueJS) para fazer funcionar

**Comment by LucasLeandro1204** [comment]
# You (kinda) Don't Know Vue

Descubra features e patterns do `Vue` que simplificam a sua vida, saiba o que são os componentes dinâmicos, slots, injeção de dependência e mais!

A Talk é bem tranquila e alguns conceitos / ideias da para relacionar com outros Frameworks, porém como eu vou falar de coisas bem `core` do Vue, é interessante ter um conhecimento básico prévio (15 min lendo a documentação).

**Comment by itsweliton** [comment]
#close
