### ISSUE TITLE
3º Meetup Vue.js Floripa - Comadre Cowork

### ISSUE THREAD

**Issue by viniciuskneves** [VueFloripa/Meetup#3]
E aí gente, beleza?

Estamos abrindo o Call for Papers para o próximo VueFloripa, que irá ocorrer na Comadre Cowork!

Para submeter sua talk baste responder essa issue com o template abaixo.
Vamos selecionar as talks com base na quatidade de :+1: que elas tiverem, portanto vote nas talks que você quer ver no dia do evento!

```
# Título (OBRIGATÓRIO)

### Resumo (ÓBRIGATÓRIO)

[Um parágrafo resumindo o conteúdo geral da sua talk.]

### Duração (OBRIGATÓRIO)

[Tempo aproximado de duração da sua talk.] --> Usaremos para ajustar no tempo de auditório disponível para o evento.

### Comentários (OPCIONAL)

[Informações extras em relação a sua talk, inclusive motivação para falar desse assunto e porquê o assunto é interessante.]
```

**Limite para envio:** 29/03

**Comment by LucasLeandro1204** [comment]
# Prevenir é melhor que remediar: Testando Vue Components

### Resumo

Vou dar uma visão geral de como testar os componentes do Vue usando um exemplo simples que consome uma API, falando um pouco sobre TDD, como criar componentes testáveis, o que são mocks, spys, etc.

### Duração

Entre 30 e 40 minutos.

### Comentários

Cada vez mais as empresas tem se ligado que um projeto sem testes é um problema dos grandes, então mesmo que a palestra seja direcionada a testar componentes Vue e por isso use algumas dependências exclusivas pra ele, o foco da palestra são os testes. Grande parte do que vai ser mostrado serve pra qualquer outro projeto com ou sem Framework (inclusive em outras linguagens, pois a ideia é a mesma).

**Comment by cbfn** [comment]
# Meu dinheiro "vuex":  Uma abordagem interativa sobre o que é o vuex e para que ele serve.

### Resumo
Darei uma visão geral sobre comunicação/interção entre componentes através de um simples e interativo gerenciador de despesas. 

### Duração
Entre 30 e 40 minutos.

### Comentários
Quando nossa aplicação cresce fica difícil manusear o estado de vários componentes e interações/comunicações entre eles. Para resolver este problema, o Vue oferece o vuex: Uma biblioteca de gerenciamento de estado inspirada no Flux, Redux e na arquitetura Elm. Falarei um pouco sobre a mesma e os problemas que ela resolve.

**Comment by gustavokrause** [comment]
# Aplicação _multi-language_ com vue-i18n

### Resumo

Exemplos práticos para aplicação multi idiomas usando `vue-i18n`.

### Duração

20~30 minutos.

### Comentários

Nível da talk: básico~médio, requer conhecimento do `vue-cli`

- Porque usar vue-i18n
- Estruturação da funcionalidade dentro do projeto Vue
- Arquivos de conteúdo para cada idioma
- Componentes para trocar linguagem
- E outros recursos úteis relacionados
