### ISSUE TITLE
4º Meetup Vue.js Floripa - Comadre Cowork

### ISSUE THREAD

**Issue by viniciuskneves** [VueFloripa/Meetup#5]
Para submeter sua talk baste responder essa issue com o template abaixo.
Vamos selecionar as talks com base na quatidade de :+1: que elas tiverem, portanto vote nas talks que você gostaria de ver no dia do Meetup!

```
# Título (OBRIGATÓRIO)

### Resumo (ÓBRIGATÓRIO)

[Um parágrafo resumindo o conteúdo geral da sua talk.]

### Duração (OBRIGATÓRIO)

[Tempo aproximado de duração da sua talk.] --> Usaremos para ajustar no tempo de auditório disponível para o evento.

### Comentários (OPCIONAL)

[Informações extras em relação a sua talk, inclusive motivação para falar desse assunto e porquê o assunto é interessante.]
```

**Limite para envio:** 01/06

**Comment by klarkc** [comment]
# Stack Vue + Loopback
### Integração do framework Node Loopback e do Vue

Vamos criar passo a passo um blog usando o framework Loopback e o Vue

### 45 min

### Comentários

É a stack que usamos na InCuca, e gostamos da flexibilidade do Loopback funcionar em qualquer banco de dados relacional ou não. Sentimos que esse framework tem uma ótima sinergia com o Vue, e criamos um template com rotas, autenticação e outras coisinhas, para usar como base dos nossos projetos.

**Comment by kuroski** [comment]
# TDD com VueJS

### Resumo
1. Introdução breve conceitual sobre testes
2. Por que testamos, o que testamos e como testamos o front
3. Como testar utilizando o Vuex
4. Vue Test Utils
5. HandsOn, será criada uma aplicação simples ao vivo com TDD para por em prática o que foi falado

Estarei focando mais na parte de testes em sí, e não ficarei necessariamente ensinando como o Vue funciona ou o que é Vuex, essas coisas irão ser faladas bem superficialmente.

A aplicação feita será BEM simples, porém eu me esforçarei para trazer o máximo dos conceitos básicos.

### Duração
60 minutos

### Comentários (OPCIONAL)
- Gostaria de falar e mostrar sobre este assunto, pois sinto que muitas pessoas acabam não dando a devida importântica para testes no front
- Também queria mostrar que podemos criar uma aplicação utilizando TDD, e que isso não é um bicho de sete cabeças, principalmente com o ambiente que o Vue nos fornece
- Para mim seria um desafio, já que eu nunca palestrei fora da empresa que trabalho
- Gosto de ensinar e principalmente da emoção de codar em quanto faço isso
- Prometi no último evento que nesse eu iria palestrar :laughing:
