### ISSUE TITLE
5º Meetup Vue.js Floripa - Linx Impulse

### ISSUE THREAD

**Issue by viniciuskneves** [VueFloripa/Meetup#7]
Para submeter sua talk baste responder essa issue com o template abaixo.
Vamos selecionar as talks com base na quatidade de :+1: que elas tiverem, portanto vote nas talks que você gostaria de ver no dia do Meetup!

```
# Título (OBRIGATÓRIO)

### Resumo (ÓBRIGATÓRIO)

[Um parágrafo resumindo o conteúdo geral da sua talk.]

### Duração (OBRIGATÓRIO)

[Tempo aproximado de duração da sua talk.] --> Usaremos para ajustar no tempo de auditório disponível para o evento.

### Comentários (OPCIONAL)

[Informações extras em relação a sua talk, inclusive motivação para falar desse assunto e porquê o assunto é interessante.]
```

**Limite para envio:** 28/09

**Comment by klarkc** [comment]
# Integração do framework Node Loopback e do Vue

### Resumo
Vamos criar passo a passo um blog usando o framework Loopback e o Vue

### Duração
45 min

### Comentários
É a stack que usamos na InCuca, e gostamos da flexibilidade do Loopback funcionar em qualquer banco de dados relacional ou não. Sentimos que esse framework tem uma ótima sinergia com o Vue, e criamos um template com rotas, autenticação e outras coisinhas, para usar como base dos nossos projetos.

**Comment by cbfn** [comment]
# Desenvolvendo aplicações móveis com o NativeScript + Vue.js

### Resumo

Recentemente o NativeScript lançou a versão 2.0 do NativeScript-Vue. Além de melhorias no template, também houve integração com o Sidekick, HMR, suporte a frames, components funcionais, DevTools e novas documentações. Nesta talk darei uma abordagem inicial de como desenvolver aplicações totalmente móveis utilizando o NativeScript-Vue.

### Duração

30 min

### Comentários

Depois de um certo tempo trabalhando com o Angular 5+ comecei a me aventurar na criação de aplicações móveis utilizando o NativeScript. Foi então que comecei a brincar com ambas as versões (Angular e Vue.js). E o resultado, embora eu já soubesse, foi esmagador e você vai saber o por quê.
