### ISSUE TITLE
6º Meetup Vue.js Floripa - Valtech

### ISSUE THREAD

**Issue by viniciuskneves** [VueFloripa/Meetup#8]
Para submeter sua talk baste responder essa issue com o template abaixo.
Vamos selecionar as talks com base na quatidade de :+1: que elas tiverem, portanto vote nas talks que você gostaria de ver no dia do Meetup!

```
# Título (OBRIGATÓRIO)

### Resumo (ÓBRIGATÓRIO)

[Um parágrafo resumindo o conteúdo geral da sua talk.]

### Duração (OBRIGATÓRIO)

[Tempo aproximado de duração da sua talk.] --> Usaremos para ajustar no tempo de auditório disponível.

### Comentários (OPCIONAL)

[Informações extras em relação a sua talk, inclusive motivação para falar desse assunto e porquê o assunto é interessante.]
```

**Limite para envio:** 18/05

**Comment by brucecantarim** [comment]
# Vue.js development in 2019 - Vuex, Vue Router and Typescript

### Resumo

Vue.js is changing, and distancing itself from it's competitors. It has become one of the friendliest and one of the most powerful javascript frameworks out there. This talk will cover how to work with Vue.js, Vue Router and Vuex in a daily basis, using Typescript and decorators.

Topics that will be covered:

- What's Vue.js?
- Where to start?
- Working with components
- SPAs and Vue Router
- State Management and Vuex
- Sass Variables in Vue
- Packing with Electron

### Duração

Aproximadamente 50 minutos.

### Comentários

Essa talk é um repeteco da minha palestra na TDC deste ano, na trilha Web / Frontend.
A principal motivação é passar um pouco do conhecimento que aprendi na prática trabalhando com Vue.js e Typescript, e as práticas que adotamos nos projetos na ArcTouch.

### Slides
[Clique aqui para acessar os slides da talk](https://slides.com/brucecantarim/tdc2019)

**Comment by klarkc** [comment]
# VuePress com autenticação

### Resumo

Fazia um tempo que estava implementando um plugin pro VuePress com oAuth 2 Implicit Grant, até que descobri uma ferramenta escondida na interwebs para resolver esse problema de uma forma muito mais efetiva e simples. Vou mostrar como usei ela no VuePress.

### Duração
40 min

**Comment by iurykrieger** [comment]
# Creating a flexible and highly extendable Vue web component based design system

### Resumo
I'll be talking about a challenge that I've faced the last year: how to build a flexible and highly extendable component library along with dynamic documentation and how to allow new developers to build frontend applications without the need to extend every single library behavior.

Covered topics:
- [Storybook 5](https://medium.com/storybookjs/storybook-5-0-db1d0f9c83b8) for Vue
- Web component Vue CLI 3 [toolbox](https://cli.vuejs.org/guide/build-targets.html#web-component)
- Component mixins and inheritance
- Component customization using [scoped slots](https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots)

### Duração
45 min
